---
- name: Install dependencies
  apt:
    name:
      - dnsutils
      - python3
      - python3-yaml

- name: Create group
  group:
    name: acme-dns-pdns
    system: true

- name: Create user
  user:
    name: acme-dns-pdns
    group: acme-dns-pdns
    state: present

- name: Template script
  template:
    src: server.py.j2
    dest: /usr/local/bin/acme-dns-pdns
    owner: root
    group: root
    mode: 0755
  notify: Restart acme-dns-pdns

- name: Template configuration
  copy:
    dest: /etc/acme-dns-pdns.yml
    content: "{{ config }}"
    owner: acme-dns-pdns
    group: acme-dns-pdns
    mode: 0440
  notify: Restart acme-dns-pdns

- name: Template service
  template:
    src: acme-dns-pdns.service.j2
    dest: /etc/systemd/system/acme-dns-pdns.service
    owner: root
    group: root
    mode: 0644
  register: service
  notify: Restart acme-dns-pdns

- name: Grant access to the pdns config
  file:
    path: /etc/powerdns/pdns.conf
    group: acme-dns-pdns
    mode: g+r

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: service.changed
